version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload && alembic upgrade head"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=6Re5*Yne
      - DATABASE_NAME=fcc_fast
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRATION_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=6Re5*Yne
      - POSTGRES_DB=fcc_fast
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: